### ISSUE TITLE
Check the literature professor talks about on class

### ISSUE THREAD

**Issue by Tristan-Chow** [Tristan-Chow/Malicious-and-Benign-domain-detection#10]
See if it is doable.

**Comment by SmellyPooh** [comment]
Key takeaways:
1. CNN is the model that is the simplest and yet shows high accuracy among a couple deep learning models. 
2. For our use case, we can implement a character based CNN model similar to this one: https://towardsdatascience.com/character-level-cnn-with-keras-50391c3adf33
3. High-level instructions from the two articles the professor shared:
"The strings that we give as input to all classifiers consist of a second level domain (SLD) and a top level domain (TLD), e.g. wikipedia.org. Set the maximum length at 75 characters, padded with zeros
on the left for domains whose length is less than 75. Convert each domain name string to lower case, since domain names are case insensitive, and encode it as an ASCII code sequence of length 128, effectively representing each domain name string as a 75 by 128 matrix in which each character
corresponds to a column."

**Comment by Tristan-Chow** [comment]
Nice work!
